baseURL = "https://top7daily.com/"
languageCode = "en-us"
title = "Top7Daily"
theme = "top7theme"

[params]
  # Any custom parameters you might need in the future

[[module.imports]]
  path = "github.com/tinacms/hugo-tinacms"