baseURL = "https://top7daily.com"
languageCode = "en-us"
title = "Top7Daily"
theme = "7dailyTheme"

[server]
[[server.headers]]
for = "/admin/*"
[server.headers.values]
  Access-Control-Allow-Origin = ["*"]